### ISSUE TITLE
How to install `indexeddbshim`

### ISSUE THREAD

**Issue by imsun** [gdnmobilelab/hybrid#9]
I found you used `indexeddbshim`, but not the one in `js-src/package.json`.

It looks like packaged [IndexedDBShim-node6](https://github.com/gdnmobilelab/IndexedDBShim-node6), but can't be installed directly from GitHub because they have different package names.

So how can I install the right `indexeddbshim`?

**Comment by alastaircoote** [comment]
Sorry about that - I was using `npm link` locally and hadn't pushed the latest version. The dependencies should be correct now.

**Comment by imsun** [comment]
Thanks very much.

But you forgot to modify module names in `js-src/rollup.config.js` and `js-src/src/service-worker/globals/indexeddb.ts`.

BTW, for modules used in `IndexedDBShim-node6/rollup-ready`, like `eventtarget` or `atob`, you may move them from `devDependencies` to `dependencies`. Or they won't be installed when installing `IndexedDBShim-node6` from npm - In this project, I have to `cd node_modules/IndexedDBShim-node6 && npm install` after running `npm install` under `js-src` to install those dependencies.

**Comment by alastaircoote** [comment]
You're correct on both counts - I will update the code accordingly.

**Comment by alastaircoote** [comment]
OK, the latest commit to master should now have all of this set up correctly.
